### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by macknight** [ramsRahim/Federated-Learning#2]
[Running] python -u "c:\Users\ac\source\repos\Federated-Learning\fl_implementation.py"
2023-09-03 10:33:10.638320: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.SGD.
Traceback (most recent call last):
  File "c:\Users\ac\source\repos\Federated-Learning\fl_implementation.py", line 59, in <module>
    optimizer = SGD(lr=lr, 
  File "C:\Users\ac\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\sgd.py", line 114, in __init__
    super().__init__(
  File "C:\Users\ac\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\optimizer.py", line 1094, in __init__
    super().__init__(
  File "C:\Users\ac\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\optimizer.py", line 106, in __init__
    self._process_kwargs(kwargs)
  File "C:\Users\ac\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\optimizer.py", line 135, in _process_kwargs
    raise ValueError(
ValueError: decay is deprecated in the new Keras optimizer, please check the docstring for valid arguments, or use the legacy optimizer, e.g., tf.keras.optimizers.legacy.SGD.

**Comment by macknight** [comment]
python, pip versions?
other packages' versions?

**Comment by macknight** [comment]
from tensorflow.keras.optimizers.legacy import SGD
it can run now.
